apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvaultapp-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: keyvaultapp
  template:
    metadata:
      labels:
        app: keyvaultapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: keyvaultapp-serviceaccount
      containers:
        - name: keyvaultapp
          image: ordercontainerregistry.azurecr.io/keyvaultapp:1.0.4
          ports:
            - containerPort: 5002
          env:
            - name: UserSetting__MySecret
              valueFrom:
                secretKeyRef:
                  name: keyvault-secrets
                  key: UserSetting__MySecret
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
            requests:
              memory: "128Mi"
              cpu: "150m"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secrets"
