apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    #useVMManagedIdentity: "false"
    clientID: "abb08ea7-d460-49a8-a242-e667cda6ef8e" # your user-assigned managed identity client ID
    keyvaultName: "myOrderkeyvault"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: UserSetting--MySecret
          objectType: secret
    tenantId: 1046fb1f-882c-4640-881d-d2f993263e1a         #<YOUR_TENANT_ID>
  secretObjects:                     # <-- This creates a K8s secret from the Key Vault secret
    - secretName: keyvault-secrets  # Kubernetes Secret name
      type: Opaque
      data:
        - objectName: UserSetting--MySecret
          key: UserSetting__MySecret
