apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvaultapp-serviceaccount
  annotations:
    azure.workload.identity/client-id: abb08ea7-d460-49a8-a242-e667cda6ef8e
  labels:
    azure.workload.identity/use: "true"